### ISSUE TITLE
Syntax error when creating models : why ?

### ISSUE THREAD

**Issue by nklamann** [MarcoMuellner/openapi-python-generator#82]
**Describe the bug**
Syntax errors during processing
**To Reproduce**
* copy the attached OpenAPI File in a directory
[Paperless-ngx_rest_api_v6.yaml.txt](https://github.com/user-attachments/files/18150219/Paperless-ngx_rest_api_v6.yaml.txt) and remove the .txt extension
* start  openapi-python-generator with this File
* The program generates a lot of python but throws the following syntax errors
```
Error in model BlankEnum: invalid syntax (<string>, line 5)
Error in model OutputTypeEnum: cannot assign to expression here. Maybe you meant '==' instead of '='? (<string>, line 7)
Error in model UnpaperCleanEnum: cannot assign to expression here. Maybe you meant '==' instead of '='? (<string>, line 6)
```
**Expected behavior**
No syntax errors.

The models look like this in the schema:
```yaml
    BlankEnum:
      enum:
      - ''
``` 

```yaml
    OutputTypeEnum:
      enum:
      - pdf
      - pdfa
      - pdfa-1
      - pdfa-2
      - pdfa-3
      type: string
      description: |-
        * `pdf` - pdf
        * `pdfa` - pdfa
        * `pdfa-1` - pdfa-1
        * `pdfa-2` - pdfa-2
        * `pdfa-3` - pdfa-3
```

```yaml
    UnpaperCleanEnum:
      enum:
      - clean
      - clean-final
      - none
      type: string
      description: |-
        * `clean` - clean
        * `clean-final` - clean-final
        * `none` - none
```

**Desktop (please complete the following information):**

 - Version openapi-python-generator, version 1.1.0

**Additional context**
 * The file validates with 'vacuum' <https://quobix.com/vacuum/about/> with a bunch of warnings but no errors.
 * The pydantic datamodel-codegenerator  <https://docs.pydantic.dev/latest/integrations/datamodel_code_generator/#example> does not balk at this yaml file and generates the enum (but not very nicely)
